/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.continuada3;
import com.mycompany.continuada3.modelo.Funcionario;
import com.mycompany.continuada3.modelo.Produto;
import com.mycompany.continuada3.modelo.Vendedor;

import java.util.List;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 *
 * @author Aluno
 */
public class TelaGerencia extends javax.swing.JFrame {
    
    Conexao conexao = new Conexao();
    JdbcTemplate vConexao = new JdbcTemplate(conexao.getvConexao());

    /**
     * Creates new form TelaGerencia
     */
    public TelaGerencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGer = new javax.swing.JToggleButton();
        btnRea = new javax.swing.JToggleButton();
        btnGerF = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGer.setText("Venda de produto");
        btnGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerActionPerformed(evt);
            }
        });

        btnRea.setText("Reabastecer estoque");
        btnRea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaActionPerformed(evt);
            }
        });

        btnGerF.setText("Cadastrar funcionario");
        btnGerF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerFActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGerF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jMensagem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButton1)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnGer)
                .addGap(29, 29, 29)
                .addComponent(btnRea)
                .addGap(29, 29, 29)
                .addComponent(btnGerF)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jMensagem)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerActionPerformed
        dispose();
        TelaProduto tela = new TelaProduto();
        tela.setVisible(true);
        
        tela.jProduto.removeAllItems();
        tela.jQuantidade.removeAllItems();
        
        List<Produto> lista = vConexao.query("Select * from produtos", new BeanPropertyRowMapper(Produto.class));
        for(Produto prod: lista)
        {
            tela.jProduto.addItem(prod.getNome()); 
            tela.jDesc.setText(prod.getDescricao());
            tela.jDesc.setLineWrap(true); 
            
            for (int i = 1; i < prod.getQuantidade(); i++) {
                tela.jQuantidade.addItem(String.valueOf(i));
            }
        }
        
        
    }//GEN-LAST:event_btnGerActionPerformed

    private void btnReaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaActionPerformed
        dispose();
        TelaEstoque tela = new TelaEstoque();
        tela.setVisible(true);
        
        tela.jEstoque.removeAllItems();
        
        List<Produto> lista = vConexao.query("Select * from produtos", new BeanPropertyRowMapper(Produto.class));
        for(Produto prod: lista)
        {
            tela.jEstoque.addItem(prod.getNome()); 
            tela.jDescE.setText(prod.getDescricao());
            tela.jDescE.setLineWrap(true);
            tela.jQtnE.setText(String.valueOf(prod.getQuantidade()));

            
        }
    }//GEN-LAST:event_btnReaActionPerformed

    private void btnGerFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerFActionPerformed
        dispose();
        TelaCadastro tela = new TelaCadastro();
        tela.setVisible(true);
    }//GEN-LAST:event_btnGerFActionPerformed
    
    public static void fechar()
    {
        TelaGerencia tela = new TelaGerencia();
        tela.setVisible(true);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton btnGer;
    public javax.swing.JToggleButton btnGerF;
    public javax.swing.JToggleButton btnRea;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jMensagem;
    // End of variables declaration//GEN-END:variables
}
